Add instructions to deploy de content of the `bin` directory
jobteaser/ci-connector pull request #13
Opened 2019-06-07 15:00 UTC by rossille

2019-06-07 15:05 UTC, clook requested changes

2019-06-07 15:05 UTC, clook commented on README.md
> +| :warning: The scripts in the `bin` folder are not inculded in the docker image, but released via a ConfigMap. After changing them, you need to run `make release-notification` to deploy your local v
Typo on "included".
```suggestion
| :warning: The scripts in the `bin` folder are not included in the docker image, but released via a ConfigMap. After changing them, you need to run `make release-notification` to deploy your local version of the scripts, so be careful that your local version is up to date.
```

2019-06-11 08:43 UTC, tauffredou approved these changes

2019-06-11 08:47 UTC, clook approved these changes
:+1:

2019-06-13 21:50 UTC, merged